sudo: required
services:
  - docker

before_install:
  - docker build -t rnwolfe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run rnwolfe/react-test npm test -- --coverage

after_success:
  # Build images
  - docker build -t rnwolfe/multi-client ./client
  - docker build -t rnwolfe/multi-server ./server
  - docker build -t rnwolfe/multi-worker ./worker
  - docker build -t rnwolfe/multi-nginx ./nginx
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # Push images to docker hub
  - docker push rnwolfe/multi-client
  - docker push rnwolfe/multi-server
  - docker push rnwolfe/multi-worker
  - docker push rnwolfe/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-077452302813
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
